"""empty message

Revision ID: 02c438fef0a8
Revises: 8e5ea8b6c3ca
Create Date: 2024-02-06 01:13:28.205897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c438fef0a8'
down_revision = '8e5ea8b6c3ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_file', schema=None) as batch_op:
        batch_op.drop_constraint('patient_file_veterinary_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['veterinary_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_file', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('patient_file_veterinary_id_fkey', 'veterinary', ['veterinary_id'], ['id'])

    # ### end Alembic commands ###
