"""empty message

Revision ID: 031e38b07490
Revises: 2425fa21be87
Create Date: 2024-01-29 07:36:24.815156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031e38b07490'
down_revision = '2425fa21be87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
