"""empty message

Revision ID: 41b29b35a5ed
Revises: e176b17b1820
Create Date: 2024-02-05 18:21:58.226094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41b29b35a5ed'
down_revision = 'e176b17b1820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('veterinarian_id', sa.Integer(), nullable=False),
    sa.Column('owner_name', sa.String(length=200), nullable=False),
    sa.Column('owner_phone', sa.String(length=20), nullable=False),
    sa.Column('owner_email', sa.String(length=200), nullable=False),
    sa.Column('owner_address', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], ),
    sa.ForeignKeyConstraint(['veterinarian_id'], ['veterinary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_file')
    # ### end Alembic commands ###
