"""empty message

Revision ID: 8e5ea8b6c3ca
Revises: ef6aa13c6fd0
Create Date: 2024-02-06 00:23:30.288650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e5ea8b6c3ca'
down_revision = 'ef6aa13c6fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veterinary', schema=None) as batch_op:
        batch_op.drop_constraint('veterinary_email_key', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veterinary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('veterinary_email_key', ['email'])

    # ### end Alembic commands ###
