"""empty message

Revision ID: bb1f5195b14d
Revises: 031e38b07490
Create Date: 2024-01-30 01:21:51.595624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb1f5195b14d'
down_revision = '031e38b07490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=300), nullable=True))
        batch_op.drop_column('disabilities')
        batch_op.drop_column('medical_history')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medical_history', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('disabilities', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
