"""empty message

Revision ID: e03974fdaae1
Revises: 41b29b35a5ed
Create Date: 2024-02-05 18:43:52.303776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e03974fdaae1'
down_revision = '41b29b35a5ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veterinary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=200), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veterinary', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
